name: secure_window
description: Secure app content visibility when user leave app. It will hide content
  in the app switcher and display a frost barrier above locked content when the user get backs to your application
version: 1.0.1
homepage: https://github.com/neckaros/secure_window

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: org.jezequel.secure_window
        pluginClass: SecureWindowPlugin
      ios:
        pluginClass: SecureWindowPlugin  
